#
# Run 'make help' for help on variables and targets
#
TOP = $(shell pwd)

# which klone version?
KLONE_VERSION ?= 2.4.0

# set the following as needed (wget should be ok on most platforms)
#export FETCH_CMD = curl -O
#export FETCH_CMD = ftp
#export FETCH_CMD = fetch
export FETCH_CMD = wget

# set the name of the daemon program (otherwise "kloned" will be used)
# KLONE_DAEMON_NAME = myapp

# configure script arguments (try ./configure --help)
# KLONE_CONF_ARGS ?= --install_daemon_only --prefix=/my/install/dir

# import arguments (any argument supported by klone import utility is allowed)
# KLONE_IMPORT_ARGS ?= 

# cross compile
# MAKL_PLATFORM ?= 
# or provide custom toolchain file
# KLONE_CUSTOM_TC ?=

# embedded fs (will be created if it does not exist)
WEBAPP_DIR = $(TOP)/webapp

# also build the following subdirs
# SUBDIR = $(TOP)/libhelp

# compiler and linker flags
# WEBAPP_CFLAGS = -I$(TOP)/
# WEBAPP_LDFLAGS = 
# WEBAPP_LDADD = $(TOP)/libhelp/libhelp.a

include klapp.mk

klapp.mk: ; $(FETCH_CMD) http://koanlogic.com/klone/klapp.mk
