# $Id: Makefile,v 1.3 2007/08/07 14:47:10 tat Exp $

include common.mk
include ../../Makefile.conf

MANFILES = klone.1 kloned.8 kloned.conf.5

ifdef INSTALL_DAEMON_ONLY
NO_INSTALL = true
endif

include man.mk
