# $Id: Makefile,v 1.1 2005/09/09 15:26:13 tat Exp $
include ../Makefile.conf

INCS = addr.h backend.h broker.h cgi.h codec.h codgzip.h config.h debug.h \
 do.h emb.h embpage.h field.h header.h http.h io.h ioprv.h klone.h md5.h  \
 mime_map.h network.h os.h page.h parser.h paths.h.in queue.h request.h   \
 response.h run.h server.h ses_prv.h session.h str.h supplier.h           \
 sysqueue.h timer.h tls.h tlsprv.h translat.h uri.h utils.h var.h         \
 varprv.h vars.h

include incs.mk
