# $Id: Makefile,v 1.3 2005/10/06 11:33:09 tho Exp $

SUBDIR =    \
 libbackend \
 libcodec   \
 libemb     \
 libhttp    \
 libio      \
 libos      \
 libpage    \
 libtls     \
 libtrans   \
 libutils   \
 libklog    \
 kloned     \
 tools

include subdir.mk
