# $Id: Makefile,v 1.6 2006/04/22 13:14:46 tat Exp $

SUBDIR =    \
 libutils   \
 libbackend \
 libcodec   \
 libemb     \
 libhttp    \
 libio      \
 libpage    \
 libtls     \
 libtrans   \
 libklog    \
 tools      \
 kloned 


include subdir.mk
