# $Id: Makefile,v 1.3 2006/01/31 17:15:33 tho Exp $ 

include common.mk
include ../Makefile.conf
include Makefile-webapp

SRCS = ${WEBAPP_SRCS}
CFLAGS += ${WEBAPP_CFLAGS}
LDADD += ${WEBAPP_LDADD}

LIB = webapp

include lib.mk
